"""create_hangy_tables

Revision ID: 20260826_01
Revises: 20260816_01
Create Date: 2026-08-26 19:10:02.152769
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = "20260826_01"
down_revision: str | Sequence[str] | None = '20260826_01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('tag_type', sa.Enum('MACRO', 'MICRO', name='tagtypeenum'), nullable=False),
    sa.Column('tag_parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tag_parent_id'], ['tag.tag_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_type', sa.Enum('PERSONAL', 'BUSINESS', name='usertypeenum'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userroleenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('business_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('business_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index('idx_business_profile_business_location', 'business_profile', ['business_location'], unique=False, postgresql_using='gist')
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_creator_id', sa.UUID(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('event_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('event_status', sa.Enum('DRAFT', 'CREATED', 'CANCELLED', 'FINISHED', name='eventstatusenum'), nullable=False),
    sa.Column('event_privacy', sa.Enum('PUBLIC', 'PRIVATE', 'INVITE_ONLY', name='eventprivacyenum'), nullable=False),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_creator_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_event_event_location', 'event', ['event_location'], unique=False, postgresql_using='gist')
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CONNECTION_REQUEST', 'EVENT_INVITE', 'EVENT_PARTICIPATION_REQUEST', 'EVENT_REQUEST_APPROVED', 'EVENT_REQUEST_REJECTED', 'EVENT_PARTICIPANT_CANCELLED', 'EVENT_PARTICIPANT_REMOVED', 'EVENT_CANCELLED', name='notificationtypeenum'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('person_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('user_connection',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'PENDING', 'REJECTED', name='userconnectionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('user_tag',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('connection_notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['user_connection.connection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('event_cancelled_notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('event_invite_link',
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('event_invite_notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('event_participant',
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'REMOVED', name='eventparticipantstatusenum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event_participant')
    )
    op.create_table('event_tag',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id')
    )
    op.create_table('report',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_creator_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_event_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('SPAM', 'HARASSMENT', 'INAPPROPRIATE_CONTENT', 'FAKE_PROFILE', 'HATE_SPEECH', 'MISLEADING_EVENT', 'SAFETY_CONCERN', 'OTHER', name='reporttypeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'REJECTED', name='reportstatusenum'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_creator_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_event_id'], ['event.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('user_follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followed_business_id'], ['business_profile.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_business_id')
    )
    op.create_table('event_experience',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('event_participant_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_participant_id'], ['event_participant.participant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('event_participant_notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participant.participant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('experience_images',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['event_experience.experience_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('experience_images')
    op.drop_table('event_participant_notification')
    op.drop_table('event_experience')
    op.drop_table('user_follows')
    op.drop_table('report')
    op.drop_table('event_tag')
    op.drop_table('event_participant')
    op.drop_table('event_invite_notification')
    op.drop_table('event_invite_link')
    op.drop_table('event_cancelled_notification')
    op.drop_table('connection_notification')
    op.drop_table('user_tag')
    op.drop_table('user_connection')
    op.drop_table('person_profile')
    op.drop_table('notification')
    op.drop_index('idx_event_event_location', table_name='event', postgresql_using='gist')
    op.drop_table('event')
    op.drop_index('idx_business_profile_business_location', table_name='business_profile', postgresql_using='gist')
    op.drop_table('business_profile')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
