"""add tag type and parent constraint

Revision ID: 20260830_01
Revises: 20260830_01
Create Date: 2026-08-30 18:33:47.949098
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260830_01"
down_revision: str | Sequence[str] | None = "20260830_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tag",
        sa.Column(
            "tag_type", sa.Enum("MACRO", "MICRO", name="tagtypeenum"), nullable=False
        ),
    )
    op.create_index("ix_tag_tag_parent_id", "tag", ["tag_parent_id"], unique=False)
    op.create_check_constraint(
        "ck_tag_macro_micro_parent",
        "tag",
        "(tag_type = 'MACRO' AND tag_parent_id IS NULL) OR "
        "(tag_type = 'MICRO' AND tag_parent_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_tag_macro_micro_parent", "tag", type_="check")
    op.drop_index("ix_tag_tag_parent_id", table_name="tag")
    op.drop_column("tag", "tag_type")
    # ### end Alembic commands ###
