"""20260908_01_add_event_invite_link_created_by

Revision ID: 20260909_01
Revises: 20260902_02
Create Date: 2026-09-09 11:57:59.650010
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260909_01"
down_revision: str | Sequence[str] | None = "20260902_02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_invite_link", sa.Column("created_by", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "event_invite_link",
        "user",
        ["created_by"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event_invite_link", type_="foreignkey")
    op.drop_column("event_invite_link", "created_by")
    # ### end Alembic commands ###
