from enum import Enum

class UserTypeEnum(str, Enum):
    PERSONAL = "PERSONAL"
    BUSINESS = "BUSINESS"

class UserRoleEnum(str, Enum):
    USER = "USER"
    ADMIN = "ADMIN"

class EventPrivacyEnum(str, Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    INVITE_ONLY = "INVITE_ONLY"

class EventStatusEnum(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    CANCELLED = "CANCELLED"
    FINISHED = "FINISHED"

class EventParticipantStatusEnum(str, Enum):
    INVITED = "INVITED"
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    REMOVED = "REMOVED"

class UserConnectionStatusEnum(str, Enum):
    CONFIRMED = "CONFIRMED"
    PENDING = "PENDING"
    REJECTED = "REJECTED"

class TagTypeEnum(str, Enum):
    MACRO = "MACRO"
    MICRO = "MICRO"

class ReportTypeEnum(str, Enum):
    SPAM = "SPAM"
    HARASSMENT = "HARASSMENT"
    INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT"
    FAKE_PROFILE = "FAKE_PROFILE"
    HATE_SPEECH = "HATE_SPEECH"
    MISLEADING_EVENT = "MISLEADING_EVENT"
    SAFETY_CONCERN = "SAFETY_CONCERN"
    OTHER = "OTHER"

class ReportStatusEnum(str, Enum):
    PENDING = "PENDING"
    REVIEWED = "REVIEWED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"

class NotificationTypeEnum(str, Enum):
    CONNECTION_REQUEST = "CONNECTION_REQUEST"
    EVENT_INVITE = "EVENT_INVITE"
    EVENT_PARTICIPATION_REQUEST = "EVENT_PARTICIPATION_REQUEST"
    EVENT_REQUEST_APPROVED = "EVENT_REQUEST_APPROVED"
    EVENT_REQUEST_REJECTED = "EVENT_REQUEST_REJECTED"
    EVENT_PARTICIPANT_CANCELLED = "EVENT_PARTICIPANT_CANCELLED"
    EVENT_PARTICIPANT_REMOVED = "EVENT_PARTICIPANT_REMOVED"
    EVENT_CANCELLED = "EVENT_CANCELLED"